version: '3.8'

services:
  rtmediaproxy:
    build: .
    network_mode: "host"
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      # Mount database volume for persistence
      - ./rtmediaproxy_server/database.sqlite:/app/server/database.sqlite
    restart: unless-stopped
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
  broadcast-box:
    environment:
    - HTTP_ADDRESS="127.0.0.1:8081"
    #- INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP=yes
    image: seaduboi/broadcast-box:latest
    hostname: broadcast-box
    container_name: broadcast-box
    network_mode: "host"
    privileged: true
    env_file: .env